use CAMPING;
CREATE TABLE 'ACTICAMPING' ('NumCamping' INTEGER NOT NULL, 'NumActivite' INTEGER NOT NULL, 'PrixActivite' REAL NOT NULL, PRIMARY KEY('NumActivite', AUTOINCREMENT) );
CREATE TABLE ACTICAMPING (NumCamping INTEGER NOT NULL, NumActivite INTEGER NOT NULL, PrixActivite REAL NOT NULL, PRIMARY KEY(NumActivite, AUTOINCREMENT) );
CREATE TABLE ACTICAMPING (NumCamping INTEGER NOT NULL, NumActivite INTEGER NOT NULL, PrixActivite REAL NOT NULL, PRIMARY KEY(NumActivite, AUTO_INCREMENT) );
CREATE TABLE ACTICAMPING (NumCamping INTEGER NOT NULL AUTOINCREMENT, NumActivite INTEGER NOT NULL, PrixActivite REAL NOT NULL, PRIMARY KEY(NumActivite) );
CREATE TABLE ACTICAMPING (NumCamping INTEGER NOT NULL AUTO_INCREMENT, NumActivite INTEGER NOT NULL, PrixActivite REAL NOT NULL, PRIMARY KEY(NumActivite) );
CREATE TABLE ACTICAMPING (NumCamping INTEGER NOT NULL, NumActivite INTEGER NOT NULL AUTO_INCREMENT, PrixActivite REAL NOT NULL, PRIMARY KEY(NumActivite) );
DROP TABLE ACTICAMPING;
CREATE TABLE ACTICAMPING (NumCamping INTEGER NOT NULL, NumActivite INTEGER NOT NULL AUTO_INCREMENT, PrixActivite REAL NOT NULL, PRIMARY KEY(NumActivite, NumCamping) );
CREATE TABLE ACTIVITE (NumActivite INTEGER NOT NULL, NomActivite INTEGER NOT NULL, TypeActivite VARCHAR(50) NOT NULL, PRIMARY KEY(NumActivite) );
DROP TABLE ACTICAMPING;
CREATE TABLE ACTICAMPING (NumCamping INTEGER NOT NULL, NumActivite INTEGER NOT NULL, PrixActivite REAL NOT NULL, PRIMARY KEY(NumActivite, NumCamping) );
CREATE TABLE CAMPING (NumCamping INTEGER NOT NULL AUTO_INCREMENT, NomCamping VARCHAR(50) NOT NULL, AddrCamping VARCHAR(1024) NOT NULL, TelCamping VARCHAR(50) NOT NULL, DateOuv DATE NOT NULL, DateFerm DATE NOT NULL, NbEtoiles INTEGER NOT NULL, QualiteFrance VARCHAR(50) NOT NULL);
CREATE TABLE CAMPING (NumCamping INTEGER NOT NULL AUTO_INCREMENT, NomCamping VARCHAR(50) NOT NULL, AddrCamping VARCHAR(1024) NOT NULL, TelCamping VARCHAR(50) NOT NULL, DateOuv DATE NOT NULL, DateFerm DATE NOT NULL, NbEtoiles INTEGER NOT NULL, QualiteFrance VARCHAR(50) NOT NULL, PRIMARY KEY(NumCamping));
INSERT INTO ACTICAMPING (NumCamping, NumActivite, PrixActivite) VALUES (1, 101, 20.50);
INSERT INTO ACTICAMPING (NumCamping, NumActivite, PrixActivite) VALUES (1, 102, 15.75);
INSERT INTO ACTICAMPING (NumCamping, NumActivite, PrixActivite) VALUES (2, 101, 18.00);
INSERT INTO ACTIVITE (NumActivite, NomActivite, TypeActivite) VALUES (101, "Randonnée pédestre", "Plein air");
DROP TABLE ACTIVITE;
CREATE TABLE ACTIVITE (NumActivite INTEGER NOT NULL, NomActivite VARCHAR(256) NOT NULL, TypeActivite VARCHAR(50) NOT NULL, PRIMARY KEY(NumActivite) );
INSERT INTO ACTIVITE (NumActivite, NomActivite, TypeActivite) VALUES (101, "Randonnée pédestre", "Plein air");
INSERT INTO ACTIVITE (NumActivite, NomActivite, TypeActivite) VALUES (102, "Escalade", "Aventure");
INSERT INTO ACTIVITE (NumActivite, NomActivite, TypeActivite) VALUES (103, "Yoga", "Bien-être");
INSERT INTO CAMPING (NumCamping, NomCamping, AddrCamping, TelCamping, DateOuv, DateFerm, NbEtoiles, QualiteFrance)VALUES ();
INSERT INTO CAMPING (NomCamping, AddrCamping, TelCamping, DateOuv, DateFerm, NbEtoiles, QualiteFrance) VALUES ("Le Paradis", "123 Rue de la Forêt", "01 23 45 67 89", "2023-05-01", "2023-10-31", 4, "Excellente");
INSERT INTO CAMPING (NomCamping, AddrCamping, TelCamping, DateOuv, DateFerm, NbEtoiles, QualiteFrance) VALUES ("Belle Nature", "456 Avenue des Montagnes", "98 76 54 32 10", "2023-06-15", "2023-09-30", 3, "Bonne");
SELECT * FROM Camping
SELECT NomCamping FROM Camping LIMIT 1;
use CAMPING; SELECT NomCamping FROM Camping LIMIT 1;
 CREATE TABLE CAMPING (NumCamping INTEGER NOT NULL AUTO_INCREMENT, NomCamping VARCHAR(50) NOT NULL, AddrCamping VARCHAR(1024) NOT NULL, TelCamping VARCHAR(50) NOT NULL, DateOuv DATE NOT NULL, DateFerm DATE NOT NULL, NbEtoiles INTEGER NOT NULL, QualiteFrance VARCHAR(50) NOT NULL, PRIMARY KEY(NumCamping));
use CAMPING; SELECT NomCamping FROM CAMPING LIMIT 1;
use CAMPING; SELECT * FROM CAMPING LIMIT 1;
use CAMPING; SELECT * FROM CAMPING LIMIT 2;
CREATE USER prof;
DELETE prof
exit
aaaaaaaaaaaaaaaaa;
DELETE prof   exit                 aaaaaaaaaaaaaaaaa;
DROP prof
;
DROP USER prof;
CREATE USER prof IDENTIFIED BY `pwdprof`
;
CREATE USER prof IDENTIFIED BY "pwdprof"
;
CREATE USER prof IDENTIFIED BY 'pwdprof'
;
CREATE USER prof@s103 IDENTIFIED BY 'pwdprof'
;
SELECT * FROM CAMPING
;
use CAMPING;
GRANT ALL PRIVILEGES ON 'CAMPING'.* TO 'prof'@s103
;
GRANT ALL PRIVILEGES ON CAMPING.* TO prof@s103
;
use CAMPING;
FLUSH PRIVILEGES;
use CAMPING;
edxit
;
SHOW GRANTS FOR 'prof@s103'
;
GRANT ALL PRIVILEGES ON CAMPING.* TO prof@localhost
;
GRANT ALL PRIVILEGES ON CAMPING.* TO prof@s103
;
GRANT ALL PRIVILEGES ON *.* TO prof@s103
;
GRANT ALL PRIVILEGES ON *.* TO 'prof'@s103
;
GRANT ALL PRIVILEGES ON *.* TO 'prof'@s103
;
GRANT ALL PRIVILEGES ON *.* TO 'prof'@s103
;
FLUSH PRIVILEGES;